


conda_envs:
            bwa: "{MODSDIR}/envs/bwa-0.7.17.yaml"
            samtools: "{MODSDIR}/envs/samtools-1.9.yaml"
            
        threads:
            bwa_mem: 4
            samtools: 1

